name = "Sborka67"
author = "Me"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4202b742acd0ad63f8c7bd4f59b696c71abb23a7195a7f99d88dcf6df2df5eb9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
